#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PracticaMVC.Movil.Droid.Resource", IsApplication=true)]

namespace PracticaMVC.Movil.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int back_icon = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int basura2_icon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int basura_icon = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int buscar_icon = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int calendario_icon = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int cards1 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int cards2 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int clock_icon = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int close_icon = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int cvv = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int deny_icon = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int despliegue_icon = 2130837515;
			
			// aapt resource value: 0x7F02000D
			public const int documento_icon = 2130837517;
			
			// aapt resource value: 0x7F02000C
			public const int document_icon = 2130837516;
			
			// aapt resource value: 0x7F02000E
			public const int download_icon = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int email_icon = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int empty_top = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int fondo_login = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int gps_icon = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int home_icon = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int icon_calendario_v2 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int icon_geolocalizacion_v2 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int icon_usuario_v2 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int inicio_bottom = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int inicio_top = 2130837528;
			
			// aapt resource value: 0x7F02001A
			public const int item_consulta = 2130837530;
			
			// aapt resource value: 0x7F020019
			public const int item_Empleados = 2130837529;
			
			// aapt resource value: 0x7F02001B
			public const int item_empty = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int item_rastreo = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int item_solicitud = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int logo = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int openpay = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int pagos_top = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int password_icon = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int plane_icon = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int plus_icon = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int radio_on = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int rastreo_top = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int registro2_icon = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int registro_icon = 2130837543;
			
			// aapt resource value: 0x7F020029
			public const int rutas_top = 2130837545;
			
			// aapt resource value: 0x7F020028
			public const int ruta_icon = 2130837544;
			
			// aapt resource value: 0x7F02002A
			public const int saldos_top = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int security = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int solicitudes_top = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int user_icon = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int user_icon2 = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int view_icon = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int MainTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
