//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones_Usuarios
    {
        public int IdNotificacion { get; set; }
        public Nullable<int> IdUsuarioGeneroNotif { get; set; }
        public Nullable<int> IdUsuarioRecibeNotif { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Mensaje { get; set; }
        public Nullable<bool> Leido { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
