//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.FechasCalendario = new HashSet<FechasCalendario>();
            this.Notificaciones_Usuarios = new HashSet<Notificaciones_Usuarios>();
            this.Notificaciones_Usuarios1 = new HashSet<Notificaciones_Usuarios>();
            this.Usuarios_Permisos = new HashSet<Usuarios_Permisos>();
            this.Usuarios_Visitados = new HashSet<Usuarios_Visitados>();
        }
    
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public Nullable<int> IdPerfilRol { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdEstatusRegistro { get; set; }
        public string ImagenUsuario { get; set; }
    
        public virtual EstatusRegistros EstatusRegistros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FechasCalendario> FechasCalendario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones_Usuarios> Notificaciones_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones_Usuarios> Notificaciones_Usuarios1 { get; set; }
        public virtual Perfiles Perfiles { get; set; }
        public virtual PerfilesRoles PerfilesRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Permisos> Usuarios_Permisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Visitados> Usuarios_Visitados { get; set; }
    }
}
