//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaMVC.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EN;
    public partial class PracticaMVC_Entities : DbContext
    {
        public PracticaMVC_Entities()
            : base("name=PracticaMVC_Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstatusRegistros> EstatusRegistros { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<PerfilesRoles> PerfilesRoles { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Usuarios_Permisos> Usuarios_Permisos { get; set; }
        public virtual DbSet<Usuarios_Visitados> Usuarios_Visitados { get; set; }
        public virtual DbSet<FechasCalendario> FechasCalendario { get; set; }
        public virtual DbSet<Notificaciones_Usuarios> Notificaciones_Usuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
